### PR TITLE
Pawn is valid move

### PR DESCRIPTION
**Pull request by ghost**
Wrote the is_valid? method in the Pawn model. 

Also wrote 2 tests in the piece spec file to test it.

If no objections, I will merge.

### CODE REVIEW

**Review by rwang430 — COMMENTED** [review]
shouldn't the ability to move 2 squares from the origin position be first before the advancing of a single square? or does positioning not matter in the code.

**Comment by ghost** [comment]
A pawn is also allowed to move 1 square on the first move. Either order works.

**Comment by ChrisdHahn** [comment]
Looks good to me Daniel! Great Work!

**Comment by ghost** [comment]
I understand the two checks but I don't think it's worth dealing with them right now, so I'll merge.

**Pull request merged**
