### PR TITLE
Fb omniauth

### PR DESCRIPTION
**Pull request by ghost**
Users can authenticate with Facebook by clicking the link on the devise sign in page. 

Run rake db:migrate when running locally because there's a new migration. 

There are two new gems. The main one is omniauth-facebook and there's also figaro, for hiding sensitive api keys.

I would really appreciate it if you guys could pull this branch and try it out, let me know if anything doesn't work. Slightly nervous that stuff will break in other people's environment.

### CODE REVIEW

**Comment by ghost** [comment]
Merging...(codeclimate failed test is purely stylistic)

**Comment by gretchonian** [comment]
My sign in page has two links to sign in with Facebook.
Both links lead me to an error page "The parameter app_id is required".

**Comment by ghost** [comment]
OK, that actually makes sense. The Figaro gem should have created a file called application.yml.

That file needs to have app_id and app_secret. I can give instructions on Slack.

**Comment by ghost** [comment]
Got it working for Roger after adding him as a developer on https://developers.facebook.com

**Pull request merged**
